### ISSUE TITLE
Add Cache API helper

### ISSUE THREAD

**Issue by notrab** [notrab/dumbo#9]
[Similar to Hono](https://hono.dev/docs/middleware/builtin/cache), we shoud add a caching helper!

**Comment by josephajibodu** [comment]
Would the caching API be primarily for caching responses?

**Comment by AymaneIsmail** [comment]
Hi everyone 😀,

First of all, I would like to thank you for this exciting project which I hope will grow.

I've been working on a very simple class that allows you to cache a request according to the “If-None-Match ‘(ETag) or ’If-Modified-Since” headers.


```php
<?php

namespace Dumbo;

use Psr\Http\Message\ResponseInterface;

class CacheMiddleware
{
    const HTTP_NOT_MODIFIED = 304;

    public static function withHeaders(
        string $type = 'private',
        bool   $mustRevalidate = false,
        int    $maxAge = 86400,
        bool   $strictEtag = false,
    ): callable
    {
        return function (Context $ctx, callable $next) use ($type, $mustRevalidate, $maxAge, $strictEtag): ResponseInterface {

            $request = $ctx->req;

            if ($request->method() != 'GET') {
                return $next($ctx);
            }

            $etag = $request->header('If-None-Match') ?: sprintf('"W/%s"', md5($ctx->req->getUri()));
            $lastModified = gmdate('D, d M Y H:i:s') . ' GMT';
            $cacheControlHeader = sprintf('%s, max-age=%d%s', $type, $maxAge, $mustRevalidate ? ', must-revalidate' : '');

            $ifModifiedSince = $request->header('If-Modified-Since');

            if ($etag === $request->header('If-None-Match') || ($ifModifiedSince && strtotime($ifModifiedSince) >= strtotime($lastModified))) {
                return $ctx->getResponse()
                    ->withStatus(self::HTTP_NOT_MODIFIED)
                    ->withHeader('Cache-Control', $cacheControlHeader)
                    ->withHeader('ETag', $etag)
                    ->withHeader('Last-Modified', $lastModified);
            }

            $nextResponse = $next($ctx);

            if (!$nextResponse->hasHeader('Cache-Control')) {
                $nextResponse = $nextResponse->withHeader('Cache-Control', $cacheControlHeader);
            }

            return $nextResponse
                ->withHeader('ETag', $etag)
                ->withHeader('Last-Modified', $lastModified);
        };
    }
}
```
### How it works :

- The middleware checks if the incoming request is a GET request. If it's not, it simply passes the request to the next handler without any caching logic.

- If it's a GET request, it looks for the If-None-Match and If-Modified-Since headers in the request.

- It compares these headers with the current ETag and the Last-Modified date of the resource. If they match, it returns a 304 Not Modified response, meaning the cached version is still valid, so the client can use it.

- If the headers don't match, it generates the full response and adds caching headers (Cache-Control, ETag, and Last-Modified) to help the client cache it for future requests.

- This way, it helps reduce unnecessary data transfers and speeds up subsequent requests by allowing the client to use cached data when appropriate.

### How to use it :

```php
<?php

require "vendor/autoload.php";

use Dumbo\CacheMiddleware;
use Dumbo\Dumbo;

$app = new Dumbo();

// Configure and use the CacheMiddleware
$app->use(CacheMiddleware::withHeaders(
    type: "private",
    mustRevalidate: false,
    maxAge: 3600,
    strictEtag: false
));

$app->get("/greet/:greeting", function ($c) {
    sleep(2);  // Simulate a delay to see the effect of caching
    $greeting = $c->req->param("greeting");
    $name = $c->req->query("name");

    return $c->json([
        "message" => "$greeting, $name!",
    ]);
});

$app->run();
```

I'm not sure if this is what was intended by the caching system or if this code is even relevant. What do you think?

**Comment by notrab** [comment]
One word. Epic.

**Comment by notrab** [comment]
@AymaneIsmail this is perfect!

**Comment by darkterminal** [comment]
Where is get `getUri()` come from @AymaneIsmail ?

**Comment by AymaneIsmail** [comment]
> Where is get `getUri()` come from @AymaneIsmail ?

Sorry I forgot to mention it, but I've added a method to the RequestWrapper class :

```php
class RequestWrapper implements RequestWrapperInterface
{
    // ...
    public function getUri(): string
    {
        return $this->request->getUri();
    }
}
```

**Comment by AymaneIsmail** [comment]
> @AymaneIsmail this is perfect!

Nice i will open the PR

**Comment by darkterminal** [comment]
@AymaneIsmail Amazing! :rocket: :fire:

**Comment by notrab** [comment]
Closing, this was added by @AymaneIsmail 🚀
